// This file is auto-generated by scripts/generate-picto-map.js
// Do not edit manually - run: node scripts/generate-picto-map.js

export const PICTOGRAM_IMAGE_MAP: Record<string, any> = {
  'assets/pictos/school/art.webp': require('@/assets/pictos/school/art.webp'),
  'assets/pictos/school/blackboard.webp': require('@/assets/pictos/school/blackboard.webp'),
  'assets/pictos/school/book.webp': require('@/assets/pictos/school/book.webp'),
  'assets/pictos/school/chair.webp': require('@/assets/pictos/school/chair.webp'),
  'assets/pictos/school/desk.webp': require('@/assets/pictos/school/desk.webp'),
  'assets/pictos/school/eraser.webp': require('@/assets/pictos/school/eraser.webp'),
  'assets/pictos/school/geography.webp': require('@/assets/pictos/school/geography.webp'),
  'assets/pictos/school/glue.webp': require('@/assets/pictos/school/glue.webp'),
  'assets/pictos/school/literature.webp': require('@/assets/pictos/school/literature.webp'),
  'assets/pictos/school/math.webp': require('@/assets/pictos/school/math.webp'),
  'assets/pictos/school/music-class.webp': require('@/assets/pictos/school/music-class.webp'),
  'assets/pictos/school/notebook.webp': require('@/assets/pictos/school/notebook.webp'),
  'assets/pictos/school/pencil-sharpener.webp': require('@/assets/pictos/school/pencil-sharpener.webp'),
  'assets/pictos/school/pencil.webp': require('@/assets/pictos/school/pencil.webp'),
  'assets/pictos/school/ruler.webp': require('@/assets/pictos/school/ruler.webp'),
  'assets/pictos/school/school-bag.webp': require('@/assets/pictos/school/school-bag.webp'),
  'assets/pictos/school/school-bus.webp': require('@/assets/pictos/school/school-bus.webp'),
  'assets/pictos/school/science.webp': require('@/assets/pictos/school/science.webp'),
  'assets/pictos/school/teacher.webp': require('@/assets/pictos/school/teacher.webp'),
  'assets/pictos/school/telescope.webp': require('@/assets/pictos/school/telescope.webp'),
};
